### ISSUE TITLE
Téléportations

### ISSUE THREAD

**Issue by Quozul** [Pickaria/Deepslate#15]
**Description de la fonctionnalité**
Ajout de commandes permettant aux joueurs de se téléporter.

**Général :**
- [ ] `/tpcancel` : annule la demande de téléportation, message cliquable lors de la téléportation pour annuler ;
- [x] `/spawn` : se téléporter au spawn du monde ;
- [ ] Si le joueur se déplace ou prend un dégât durant ce temps, la téléportation est annulée ;
- [x] Chaque demande doit être espacée d'un temps configurable ;

**Téléportations :**
Une demande à un temps d'expiration et doit être acceptée.  

- [x] `/tpr` : téléportation aléatoire sur la carte, sur un rayon configurable ;
- [x] `/tpa <joueur>` : envoi une demande de téléportation à un joueur ;
- [ ] `/tphere <joueur>` : envoi une demande pour qu'un joueur se téléporte à vous ;
- [x] `/tpaccept` et `/tpdeny` : accepte ou refuse une demande de téléportation ;
- [ ] Rendre le message dans le chat cliquable pour accepter ou refuser une demande ;

**Home :**
Chaque commande prend un nom de home optionnel.  
Les homes sont stockés en base de données.  

- [x] `/sethome <nom du home>` : créé un nouveau "home" ;
- [ ] `/delhome <nom du home>` : supprime un "home" ;
- [x] `/home <nom du home>` : se téléporter à un "home" ;
- [ ] Avoir une liste des homes, eventuellement dans un menu ;
- [ ] La quantité maximum de home doit être configurable dans le fichier de configuration ;

**Tarifs :**
La téléportation aléatoire sur le monde se fait contre de l'argent, 1$ permet de se téléporter aléatoirement à 10 blocs de sa position actuelle.  
Avec une valeur par défaut et minimum de 100$.

Chaque fois qu'un joueur place un nouveau home, il sera débité d'une quantité d'argent.  
Somme qui augmente plus le joueur à de homes.

**Feedback :**
Effet de nausée pendant le délai de téléportation.  
Son d'enderpearl à la fin du délai.

**Comment by AHajin** [comment]
Hier pendant mes tests j'ai découvert une anomalie sur la commande TPR qui ne fonctionne simplement plus.
Je me demande si ça n'a pas de rapport avec le fait que H2 n'est pas encore supporter par le plugin et qui provoque ce soucis.

Dans la semaine j'implémenterais sans doute /tpcancel et /spawn qui n'ont pas l'air très complexe à réaliser.

**Comment by Quozul** [comment]
> Hier pendant mes tests j'ai découvert une anomalie sur la commande TPR qui ne fonctionne simplement plus. Je me demande si ça n'a pas de rapport avec le fait que l'économie n'est pas encore supporter par le plugin et qui provoque ce soucis.

Il faut que tu appelles [la méthode `setupEconomy()`](https://github.com/Pickaria/plugin-collection/blob/master/plugins/shared/src/main/kotlin/fr/pickaria/shared/utils.kt#L7) comme fait [dans le plugin jobs](https://github.com/Pickaria/plugin-collection/blob/master/plugins/job/src/main/kotlin/fr/pickaria/job/Main.kt#L16:L17) pour initialiser l'économie dans le plugin de téléportation.

**Comment by AHajin** [comment]
Hier j'ai commit la commande Spawn et la commande RTP, aujourd'hui les commandes sethome et home, c'est en beta, mais ça fonctionne bien, à tester avec + de 1 joueurs
